theme: jekyll-theme-tactile
title: Welcome to Worasom's GitHub Page! 
description: I am an aspiring data scientist with a board background in microscopy imaging and material science characterization. I am interested in Board range of technical expertise in data science and material science. Used machine learning (ML) in
data inference, pattern identification, data driven decision-making and ML model deployment. In this page, you will find machine learning projects, 
ML class notes, and previous publications. If you have any suggestion, please leave me a message! 
